### ISSUE TITLE
libjvm.so is looked for in the wrong place

### ISSUE THREAD

**Issue by MaxNoe** [kivy/pyjnius#428]
On travis, even with `JAVA_HOME` set, the library is not found.

It is actually in:

```
/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
```

But pyjnius looks in:

```
/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/server/libjvm.so
```

**Comment by julianhess** [comment]
You need to set `JDK_HOME` to `/usr/lib/jvm/java-8-openjdk-amd64/`; setup.py does not check `JAVA_HOME`. See:

https://github.com/kivy/pyjnius/blob/afd9b42ba54791870e789a18fbfed75bde97a609/setup.py#L154

**Comment by MaxNoe** [comment]
Hey wo I need to set it at all? Why not take the java(c) that's in the PATH my default?

**Comment by MaxNoe** [comment]
Oh wait. It does. Neither is the problem here!

The problem is the additional `amd64` in the path.

**Comment by julianhess** [comment]
You need to rebuild the package with `JDK_HOME` already set as above; merely setting it after building will do nothing.

I kept running into this issue too until I dug through the source and found that the path to libjvm.so gets baked in during compilation (try running `strings jnius.cpython-37m-x86_64-linux-gnu.so | grep libjvm`)

**Comment by tshirtman** [comment]
hopefully this should be solved by the changes i did in the #443 PR, which will provide wheels able to do this check at runtime, and try to be smarter about the lookup.

**Comment by tshirtman** [comment]
Closing as i believe this to be fixed, let us know if you still have issues.

**Comment by MaxNoe** [comment]
Just commenting: the PR you lined only changes a single line of whitespace. Wrong PR?

**Comment by tshirtman** [comment]
indeed that was #444 thanks for pointing out.

**Comment by mashabelyi** [comment]
I am having the same issue with the most recent version, even after setting both `JAVA_HOME` and `JDK_HOME` to my java path: `/usr/lib/jvm/java-8-oracle`.

In my case pyjnius is looking in 
```
/usr/lib/jvm/java-8-oracle/lib/server/libjvm.so
```

but the actual path is 
```
/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server/libjvm.so
```

I tried adding `/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server` to the `PATH` env variable too. But still get the same error on import:
```
SystemError: Error calling dlopen(b'/usr/lib/jvm/java-8-oracle/lib/server/libjvm.so': b'/usr/lib/jvm/java-8-oracle/lib/server/libjvm.so: cannot open shared object file: No such file or directory'
```

**Comment by chemu-patent-ie** [comment]
I am also having an issue. This is a dependency for something else I'm trying to install.

My $JAVA_HOME and $JDK_HOME are correctly set. When I go to the path they point to and look for libjvm I see:

$ find . -name "libjvm*"
./jre/bin/classic/libjvm.so
./jre/bin/j9vm/libjvm.so
./jre/lib/amd64/classic/libjvm.so
./jre/lib/amd64/compressedrefs/libjvm.so
./jre/lib/amd64/default/libjvm.so
./jre/lib/amd64/j9vm/libjvm.so

No "server" directory at all.

SystemError: Error calling dlopen(b'/usr/lib/jvm/java-1.8.0-ibm-1.8.0.6.5-1jpp.1.el7.x86_64/lib/server/libjvm.so': b'/usr/lib/jvm/java-1.8.0-ibm-1.8.0.6.5-1jpp.1.el7.x86_64/lib/server/libjvm.so: cannot open shared object file: No such file or directory'

Is the problem my Java version or something else?

**Comment by tshirtman** [comment]
https://github.com/kivy/pyjnius/pull/520 for a tentative fix + workaround
if things go well, https://github.com/kivy/pyjnius/actions/runs/87203882 should produce wheel packages that you can test on your systems to confirm if this helps.

I added the paths you both reported, and added a system to override the value through a non standard JVM_PATH en var if that doesn't work, with a message encouraging people to report working values, hopefuly it'll allow us to understand what paths are actually used in the wild.

**Comment by tshirtman** [comment]
closing as i hope this to be fixed, if the error happens again, please open a new issue refering to this one.
